2025-04-25 21:08:10.211 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:13.345 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:16.467 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:19.601 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:20.043 WARNING (MainThread) [homeassistant.setup] Setup of recorder is taking over 10 seconds.
2025-04-25 21:08:22.729 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:25.853 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:28.976 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:32.096 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:35.223 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:38.347 ERROR (Recorder) [homeassistant.components.recorder.core] Error during connection setup: (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 927, in _setup_recorder
    self._setup_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 1437, in _setup_connection
    self.engine = create_engine(self.db_url, **kwargs, future=True)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/engine/url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:influxdb
2025-04-25 21:08:38.348 ERROR (Recorder) [homeassistant.components.recorder.core] Recorder setup failed, recorder shutting down
2025-04-25 21:08:38.349 ERROR (MainThread) [homeassistant.setup] Setup failed for 'recorder': Integration failed to initialize.
2025-04-25 21:08:39.820 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'history'. Setup failed for dependencies: ['recorder']
2025-04-25 21:08:39.820 ERROR (MainThread) [homeassistant.setup] Setup failed for 'history': Could not setup dependencies: recorder
2025-04-25 21:08:39.821 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'energy'. Setup failed for dependencies: ['history', 'recorder']
2025-04-25 21:08:39.821 ERROR (MainThread) [homeassistant.setup] Setup failed for 'energy': Could not setup dependencies: history, recorder
2025-04-25 21:08:39.821 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'logbook'. Setup failed for dependencies: ['recorder']
2025-04-25 21:08:39.821 ERROR (MainThread) [homeassistant.setup] Setup failed for 'logbook': Could not setup dependencies: recorder
2025-04-25 21:08:41.212 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Kuba-Pospiesznywp.pl@wp.pl' for tuya integration could not authenticate: Authentication failed. Please re-authenticate
2025-04-25 21:08:43.501 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. Setup failed for dependencies: ['energy', 'history', 'logbook']
2025-04-25 21:08:43.501 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': Could not setup dependencies: energy, history, logbook
2025-04-25 21:09:01.883 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.led_bulb_w509z2, light.lsc_smart_a60_rgb_cct, light.lsc_smart_a60_rgb_cct_2, light.lsc_smart_a60_rgb_cct_3 are missing or not currently available
2025-04-25 21:09:02.762 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.led_bulb_w509z2, light.lsc_smart_a60_rgb_cct, light.lsc_smart_a60_rgb_cct_2, light.lsc_smart_a60_rgb_cct_3 are missing or not currently available
2025-04-25 21:09:03.210 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.led_bulb_w509z2, light.lsc_smart_a60_rgb_cct, light.lsc_smart_a60_rgb_cct_2, light.lsc_smart_a60_rgb_cct_3 are missing or not currently available
2025-04-25 21:12:06.167 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:06.426 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436953544896] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:06.479 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:06.611 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436953538272] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:06.671 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.422 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.556 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.582 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436944887952] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:11.595 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.610 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436944887664] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:11.650 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.679 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436944887232] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:11.697 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.712 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436944891264] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:11.732 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.773 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436944890544] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:11.785 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.817 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436944893136] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:11.835 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.891 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:11.947 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.022 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.067 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Mobile/HomeAssistant, like Safari)
2025-04-25 21:12:12.078 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.135 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.197 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.226 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.275 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.337 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.378 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.407 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.440 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.467 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.504 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.557 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.607 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.638 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.692 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.732 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.770 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.818 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.861 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.927 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:12.972 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.032 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.063 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.117 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.152 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [135436945241664] from 10.42.0.1 (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2)): Disconnected: Received close message during auth phase
2025-04-25 21:12:13.167 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.230 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.280 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
2025-04-25 21:12:13.325 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.42.0.1 (10.42.0.1). Requested URL: '/auth/token'. (Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.3.2) Alamofire/5.8.0)
